# Generated by Django 5.0.2 on 2024-02-29 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('sku', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('Livros', 'Livros'), ('Filmes', 'Filmes'), ('Música', 'Música'), ('Jogos', 'Jogos'), ('Eletrônicos', 'Eletrônicos'), ('Computadores', 'Computadores'), ('Lar', 'Lar'), ('Jardim', 'Jardim'), ('Ferramentas', 'Ferramentas'), ('Mercado', 'Mercado'), ('Saúde', 'Saúde'), ('Beleza', 'Beleza'), ('Brinquedos', 'Brinquedos'), ('Crianças', 'Crianças'), ('Bebê', 'Bebê'), ('Roupas', 'Roupas'), ('Sapato', 'Sapato'), ('Jóias', 'Jóias'), ('Esportes', 'Esportes'), ('Ao ar livre', 'Ao ar livre'), ('Automotivo', 'Automotivo'), ('Industrial', 'Industrial')], max_length=50)),
                ('price', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='RatingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.client')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.supplier'),
        ),
    ]
