# Generated by Django 5.0.2 on 2024-03-01 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_name_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'verbose_name': 'Histórico de Preço'},
        ),
    ]
