# Generated by Django 5.0.2 on 2024-02-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_categorie_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Livros', 'Livros'), ('Filmes', 'Filmes'), ('Música', 'Música'), ('Jogos', 'Jogos'), ('Eletrônicos', 'Eletrônicos'), ('Computadores', 'Computadores'), ('Lar', 'Lar'), ('Jardim', 'Jardim'), ('Ferramentas', 'Ferramentas'), ('Mercado', 'Mercado'), ('Saúde', 'Saúde'), ('Beleza', 'Beleza'), ('Brinquedos', 'Brinquedos'), ('Crianças', 'Crianças'), ('Bebê', 'Bebê'), ('Roupas', 'Roupas'), ('Sapato', 'Sapato'), ('Jóias', 'Jóias'), ('Esportes', 'Esportes'), ('Ao ar livre', 'Ao ar livre'), ('Automotivo', 'Automotivo'), ('Industrial', 'Industrial')], max_length=50),
        ),
    ]
